<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AfterPub.Core\AfterPub.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AfterPub</AssemblyName>
  </PropertyGroup>

  <!-- Publish settings. The COM late binding in the Publisher engine can break under trimming. -->
  <PropertyGroup>
    <PublishTrimmed>false</PublishTrimmed>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
  </PropertyGroup>

</Project>
